# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
# ======================================GROUP PODS==========================================
def netalo_pods
  pod 'NetacomSDKs', :build_type => :dynamic_framework, :git => 'https://github.com/Netacom-NetAlo/NetaloSDKs-iOS', tag: '10.0.1'

  noti_netalo_pods
end

def noti_netalo_pods
   pod 'NotificationSDK', :build_type => :dynamic_framework, :git => 'https://github.com/Netacom-NetAlo/NotiSDKs-iOS', tag: '10.0.1'
   pod 'WebRTC', :build_type => :dynamic_framework, :git => 'https://github.com/Netacom-NetAlo/WebRTC-iOS', branch: 'main'
end

def resolver
  pod 'Resolver', :build_type => :dynamic_framework, :git => 'https://github.com/Netacom-NetAlo/Resolver-iOS'
end

# ======================================TARGET PODS==========================================
def app_pods
   pod 'MessageKit', :build_type => :dynamic_framework, :git => 'https://github.com/Netacom-NetAlo/Messagekit-iOS', branch: 'main'
  resolver
  netalo_pods
end

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  app_pods
  use_modular_headers!
end

# ============================Notification Extension================================
 def app_notification_pods
   resolver
   noti_netalo_pods
 end

 target 'NotificationExtension' do
   app_notification_pods
 end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = 'arm64 x86_64'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      '$(inherited)',
      ## dart: PermissionGroup.calendar
      #         'PERMISSION_EVENTS=1',
      ## dart: PermissionGroup.reminders
      'PERMISSION_REMINDERS=1',
      ## dart: PermissionGroup.contacts
      # 'PERMISSION_CONTACTS=0',
      ## dart: PermissionGroup.camera
      'PERMISSION_CAMERA=1',
      ## dart: PermissionGroup.microphone
      'PERMISSION_MICROPHONE=1',
      ## dart: PermissionGroup.speech
      #         'PERMISSION_SPEECH_RECOGNIZER=1',
      ## dart: PermissionGroup.photos
      'PERMISSION_PHOTOS=1',
      ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
      'PERMISSION_LOCATION=1',
      ## dart: PermissionGroup.notification
      # 'PERMISSION_NOTIFICATIONS=0',
      ## dart: PermissionGroup.mediaLibrary
      #         'PERMISSION_MEDIA_LIBRARY=1',
      ## dart: PermissionGroup.sensors
      #         'PERMISSION_SENSORS=1'
      ]
    end
  end
end
