# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_modular_headers!

  pod 'MessageKit', :git => 'https://github.com/thanhphong-tran/messagekit'
  pod 'Localize-Swift', :git => 'https://github.com/thanhphong-tran/Localize-Swift'
  pod 'Kingfisher', '~> 5.15'
  pod 'ReSwift', '~> 4.1.1'
  pod 'ReSwiftThunk', git: 'https://github.com/thanhphong-tran/ReSwift-Thunk.git', :tag => '1.1.1'
  pod 'SwipeTransition', '~> 0.4.2'
  pod 'GoogleWebRTC', '~> 1.1'
  # Local database
  pod 'Realm', '5.3.5'
  pod 'RealmSwift', '5.3.5'
  pod 'Reachability', '~> 3.2'
  # Localization 2.0
  pod 'ZIPFoundation', '~> 0.9'
  # Secret chat
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git', :commit => 'eea6884e55261bf157ad6054c72c3c51d7788d4c'
  pod 'AxolotlKit', git: 'https://github.com/signalapp/SignalProtocolKit.git', branch: 'master'
  pod 'HKDFKit', git: 'https://github.com/signalapp/HKDFKit.git'
  pod 'Curve25519Kit', git: 'https://github.com/signalapp/Curve25519Kit'
  pod 'GRKOpenSSLFramework', git: 'https://github.com/signalapp/GRKOpenSSLFramework', branch: 'mkirk/1.0.2t'
  pod 'Socket.IO-Client-Swift', '14.0.0'
#  pod 'NetaloCommonSDK', :path => '/Users/phong/Desktop/IOS/NetaloCommonSDK'
#  pod 'NetAloNotificationService', :path => '/Users/phong/Desktop/IOS/NetAloNotificationService'
#  pod 'NetaloCommonSDK', :git => 'https://github.com/thanhphong-tran/NetaloCommonSDK', branch: 'simulator'
   pod 'NetaloCommonSDK', :git => 'https://github.com/thanhphong-tran/NetaloCommonSDK', branch: 'release-v19'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'NotificationExtension' do
  
  pod 'RealmSwift', '5.3.5'
  pod 'Localize-Swift', :git => 'https://github.com/thanhphong-tran/Localize-Swift'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
